USE [master]
GO
/****** 개체: Database [GameServer] 스크립트 날짜: 2026-09-25 오후 4:44:56 ******/
CREATE DATABASE [GameServer]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GameServer', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\GameServer.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GameServer_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\GameServer_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [GameServer] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GameServer].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GameServer] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GameServer] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GameServer] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GameServer] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GameServer] SET ARITHABORT OFF 
GO
ALTER DATABASE [GameServer] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GameServer] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GameServer] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GameServer] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GameServer] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GameServer] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GameServer] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GameServer] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GameServer] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GameServer] SET  DISABLE_BROKER 
GO
ALTER DATABASE [GameServer] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GameServer] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GameServer] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GameServer] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GameServer] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GameServer] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GameServer] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GameServer] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [GameServer] SET  MULTI_USER 
GO
ALTER DATABASE [GameServer] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GameServer] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GameServer] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GameServer] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GameServer] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GameServer] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [GameServer] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [GameServer] SET QUERY_STORE = ON
GO
ALTER DATABASE [GameServer] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [GameServer]
GO
/****** 개체: Table [dbo].[Item_Meta] 스크립트 날짜: 2026-09-25 오후 4:44:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Item_Meta](
	[ItemId] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[ItemType] [tinyint] NOT NULL,
	[MaxStack] [int] NOT NULL,
 CONSTRAINT [PK_Item_Meta] PRIMARY KEY CLUSTERED 
(
	[ItemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** 개체: Table [dbo].[Player_Equipped] 스크립트 날짜: 2026-09-25 오후 4:44:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Player_Equipped](
	[PlayerId] [bigint] NOT NULL,
	[EquipSlot] [tinyint] NOT NULL,
	[ItemDbId] [bigint] NOT NULL,
	[ItemId] [int] NOT NULL,
	[EquippedAt] [datetime] NULL,
 CONSTRAINT [PK_Player_Equipped] PRIMARY KEY CLUSTERED 
(
	[PlayerId] ASC,
	[EquipSlot] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** 개체: Table [dbo].[Player_Info] 스크립트 날짜: 2026-09-25 오후 4:44:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Player_Info](
	[PlayerId] [bigint] IDENTITY(1,1) NOT NULL,
	[AccountId] [bigint] NOT NULL,
	[Name] [nvarchar](20) NOT NULL,
	[PlayerType] [int] NOT NULL,
	[Level] [int] NOT NULL,
	[Exp] [bigint] NOT NULL,
	[Hp] [int] NOT NULL,
	[Mp] [int] NOT NULL,
	[Gold] [bigint] NOT NULL,
	[CreateDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Player_Info] PRIMARY KEY CLUSTERED 
(
	[PlayerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** 개체: Table [dbo].[Player_Inventory] 스크립트 날짜: 2026-09-25 오후 4:44:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Player_Inventory](
	[ItemDbId] [bigint] IDENTITY(1,1) NOT NULL,
	[PlayerId] [bigint] NOT NULL,
	[ItemId] [int] NOT NULL,
	[Quantity] [int] NOT NULL,
	[SlotIndex] [int] NOT NULL,
	[AcquiredAt] [datetime] NOT NULL,
 CONSTRAINT [PK_Player_Inventory] PRIMARY KEY CLUSTERED 
(
	[ItemDbId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** 개체: Table [dbo].[Trade_Log] 스크립트 날짜: 2026-09-25 오후 4:44:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Trade_Log](
	[LogId] [bigint] IDENTITY(1,1) NOT NULL,
	[TradeType] [tinyint] NOT NULL,
	[FromId] [int] NULL,
	[ToPlayerDbId] [int] NOT NULL,
	[ItemId] [int] NOT NULL,
	[Quantity] [int] NOT NULL,
	[TradeAt] [datetime] NOT NULL,
 CONSTRAINT [PK_Trade_Log] PRIMARY KEY CLUSTERED 
(
	[LogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** 개체: Table [dbo].[User_Account] 스크립트 날짜: 2026-09-25 오후 4:44:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User_Account](
	[AccountId] [bigint] IDENTITY(1,1) NOT NULL,
	[LoginId] [varchar](50) NOT NULL,
	[LoginPassword] [varchar](50) NOT NULL,
	[Status] [tinyint] NOT NULL,
 CONSTRAINT [PK_User_Account] PRIMARY KEY CLUSTERED 
(
	[AccountId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** 개체: Table [dbo].[User_Info] 스크립트 날짜: 2026-09-25 오후 4:44:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User_Info](
	[AccountId] [bigint] NOT NULL,
	[LastLoginAt] [datetime] NULL,
	[CreateDate] [datetime] NOT NULL,
 CONSTRAINT [PK_User_Info] PRIMARY KEY CLUSTERED 
(
	[AccountId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** 개체: Index [IX_Player_Info_AccountDbId] 스크립트 날짜: 2026-09-25 오후 4:44:56 ******/
CREATE NONCLUSTERED INDEX [IX_Player_Info_AccountDbId] ON [dbo].[Player_Info]
(
	[AccountId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** 개체: Index [IX_Player_Info_Name] 스크립트 날짜: 2026-09-25 오후 4:44:56 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Player_Info_Name] ON [dbo].[Player_Info]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** 개체: Index [IX_Inventory_PlayerDbId] 스크립트 날짜: 2026-09-25 오후 4:44:56 ******/
CREATE NONCLUSTERED INDEX [IX_Inventory_PlayerDbId] ON [dbo].[Player_Inventory]
(
	[PlayerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** 개체: Index [IX_Trade_Log_ToPlayer] 스크립트 날짜: 2026-09-25 오후 4:44:56 ******/
CREATE NONCLUSTERED INDEX [IX_Trade_Log_ToPlayer] ON [dbo].[Trade_Log]
(
	[ToPlayerDbId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** 개체: Index [IX_User_Account_LoginId] 스크립트 날짜: 2026-09-25 오후 4:44:56 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_User_Account_LoginId] ON [dbo].[User_Account]
(
	[LoginId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Item_Meta] ADD  DEFAULT ((1)) FOR [MaxStack]
GO
ALTER TABLE [dbo].[Player_Equipped] ADD  DEFAULT (getdate()) FOR [EquippedAt]
GO
ALTER TABLE [dbo].[Player_Info] ADD  CONSTRAINT [DF_Player_Info_PlayerType]  DEFAULT ((0)) FOR [PlayerType]
GO
ALTER TABLE [dbo].[Player_Info] ADD  CONSTRAINT [DF__Player_In__Level__70DDC3D8]  DEFAULT ((1)) FOR [Level]
GO
ALTER TABLE [dbo].[Player_Info] ADD  CONSTRAINT [DF__Player_Info__Exp__71D1E811]  DEFAULT ((0)) FOR [Exp]
GO
ALTER TABLE [dbo].[Player_Info] ADD  CONSTRAINT [DF_Player_Info_Hp]  DEFAULT ((100)) FOR [Hp]
GO
ALTER TABLE [dbo].[Player_Info] ADD  CONSTRAINT [DF_Player_Info_Mp]  DEFAULT ((100)) FOR [Mp]
GO
ALTER TABLE [dbo].[Player_Info] ADD  CONSTRAINT [DF__Player_Inf__Gold__72C60C4A]  DEFAULT ((0)) FOR [Gold]
GO
ALTER TABLE [dbo].[Player_Info] ADD  CONSTRAINT [DF__Player_In__Creat__76969D2E]  DEFAULT (getdate()) FOR [CreateDate]
GO
ALTER TABLE [dbo].[Player_Inventory] ADD  DEFAULT ((1)) FOR [Quantity]
GO
ALTER TABLE [dbo].[Player_Inventory] ADD  DEFAULT (getdate()) FOR [AcquiredAt]
GO
ALTER TABLE [dbo].[Trade_Log] ADD  DEFAULT (getdate()) FOR [TradeAt]
GO
ALTER TABLE [dbo].[User_Account] ADD  DEFAULT ((0)) FOR [Status]
GO
ALTER TABLE [dbo].[User_Info] ADD  DEFAULT (getdate()) FOR [CreateDate]
GO
ALTER TABLE [dbo].[Player_Equipped]  WITH CHECK ADD  CONSTRAINT [FK_Player_Equipped_Item_Meta] FOREIGN KEY([ItemId])
REFERENCES [dbo].[Item_Meta] ([ItemId])
GO
ALTER TABLE [dbo].[Player_Equipped] CHECK CONSTRAINT [FK_Player_Equipped_Item_Meta]
GO
ALTER TABLE [dbo].[Player_Equipped]  WITH CHECK ADD  CONSTRAINT [FK_Player_Equipped_Player_Info] FOREIGN KEY([PlayerId])
REFERENCES [dbo].[Player_Info] ([PlayerId])
GO
ALTER TABLE [dbo].[Player_Equipped] CHECK CONSTRAINT [FK_Player_Equipped_Player_Info]
GO
ALTER TABLE [dbo].[Player_Info]  WITH CHECK ADD  CONSTRAINT [FK_Player_Info_User_Account] FOREIGN KEY([AccountId])
REFERENCES [dbo].[User_Account] ([AccountId])
GO
ALTER TABLE [dbo].[Player_Info] CHECK CONSTRAINT [FK_Player_Info_User_Account]
GO
ALTER TABLE [dbo].[Player_Inventory]  WITH CHECK ADD  CONSTRAINT [FK_Inventory_ItemMeta] FOREIGN KEY([ItemId])
REFERENCES [dbo].[Item_Meta] ([ItemId])
GO
ALTER TABLE [dbo].[Player_Inventory] CHECK CONSTRAINT [FK_Inventory_ItemMeta]
GO
ALTER TABLE [dbo].[Player_Inventory]  WITH CHECK ADD  CONSTRAINT [FK_Inventory_Player] FOREIGN KEY([PlayerId])
REFERENCES [dbo].[Player_Info] ([PlayerId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Player_Inventory] CHECK CONSTRAINT [FK_Inventory_Player]
GO
ALTER TABLE [dbo].[Trade_Log]  WITH CHECK ADD  CONSTRAINT [FK_Trade_Log_Item_Meta] FOREIGN KEY([ItemId])
REFERENCES [dbo].[Item_Meta] ([ItemId])
GO
ALTER TABLE [dbo].[Trade_Log] CHECK CONSTRAINT [FK_Trade_Log_Item_Meta]
GO
ALTER TABLE [dbo].[User_Info]  WITH CHECK ADD  CONSTRAINT [FK_User_Info_User_Account] FOREIGN KEY([AccountId])
REFERENCES [dbo].[User_Account] ([AccountId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[User_Info] CHECK CONSTRAINT [FK_User_Info_User_Account]
GO
USE [master]
GO
ALTER DATABASE [GameServer] SET  READ_WRITE 
GO
