// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Enum.proto

#include "Enum.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace Protocol {
}  // namespace Protocol
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_Enum_2eproto[5];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Enum_2eproto = nullptr;
const uint32_t TableStruct_Enum_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_Enum_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nEnum.proto\022\010Protocol*\227\003\n\010PacketId\022\014\n\010P"
  "KT_NONE\020\000\022\r\n\010CS_LOGIN\020\350\007\022\016\n\tCS_SIGNUP\020\351\007"
  "\022\016\n\tCS_LOGOUT\020\352\007\022\014\n\007CS_CHAT\020\353\007\022\014\n\007CS_MOV"
  "E\020\354\007\022\r\n\010CS_CMOVE\020\355\007\022\022\n\rCS_ENTER_ROOM\020\356\007\022"
  "\022\n\rCS_LEAVE_ROOM\020\357\007\022\016\n\tCS_ATTACK\020\360\007\022\024\n\017C"
  "S_CHANGE_EQUIP\020\361\007\022\r\n\010SC_LOGIN\020\320\017\022\016\n\tSC_S"
  "IGNUP\020\321\017\022\016\n\tSC_LOGOUT\020\322\017\022\022\n\rSC_ADD_OBJEC"
  "T\020\323\017\022\025\n\020SC_REMOVE_OBJECT\020\324\017\022\014\n\007SC_CHAT\020\325"
  "\017\022\023\n\016SC_MOVE_OBJECT\020\326\017\022\024\n\017SC_CMOVE_OBJEC"
  "T\020\327\017\022\016\n\tSC_ATTACK\020\330\017\022\016\n\tSC_DAMAGE\020\331\017\022\014\n\007"
  "SC_DEAD\020\332\017\022\024\n\017SC_CHANGE_EQUIP\020\333\017*u\n\tMove"
  "State\022\023\n\017MOVE_STATE_NONE\020\000\022\023\n\017MOVE_STATE"
  "_IDLE\020\001\022\022\n\016MOVE_STATE_RUN\020\002\022\023\n\017MOVE_STAT"
  "E_JUMP\020\003\022\025\n\021MOVE_STATE_ATTACK\020\004*\233\001\n\nObje"
  "ctType\022\024\n\020OBJECT_TYPE_NONE\020\000\022\026\n\022OBJECT_T"
  "YPE_PLAYER\020\001\022\027\n\023OBJECT_TYPE_MONSTER\020\002\022\023\n"
  "\017OBJECT_TYPE_NPC\020\003\022\024\n\020OBJECT_TYPE_ITEM\020\004"
  "\022\033\n\027OBJECT_TYPE_ENVIRONMENT\020\005*\232\001\n\nPlayer"
  "Type\022\024\n\020PLAYER_TYPE_NONE\020\000\022\024\n\020PLAYER_TYP"
  "E_MALE\020\001\022\026\n\022PLAYER_TYPE_FEMALE\020\002\022\027\n\023PLAY"
  "ER_TYPE_MONSTER\020\003\022\027\n\023PLAYER_TYPE_WARRIOR"
  "\020\004\022\026\n\022PLAYER_TYPE_ARCHER\020\005*\200\001\n\tEquipPart"
  "\022\023\n\017EQUIP_PART_NONE\020\000\022\024\n\020EQUIP_PART_UPPE"
  "R\020\001\022\024\n\020EQUIP_PART_LOWER\020\002\022\033\n\027EQUIP_PART_"
  "OUTFIT_SHOES\020\003\022\025\n\021EQUIP_PART_WEAPON\020\005b\006p"
  "roto3"
  ;
static ::_pbi::once_flag descriptor_table_Enum_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Enum_2eproto = {
    false, false, 1005, descriptor_table_protodef_Enum_2eproto,
    "Enum.proto",
    &descriptor_table_Enum_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_Enum_2eproto::offsets,
    nullptr, file_level_enum_descriptors_Enum_2eproto,
    file_level_service_descriptors_Enum_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Enum_2eproto_getter() {
  return &descriptor_table_Enum_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Enum_2eproto(&descriptor_table_Enum_2eproto);
namespace Protocol {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PacketId_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[0];
}
bool PacketId_IsValid(int value) {
  switch (value) {
    case 0:
    case 1000:
    case 1001:
    case 1002:
    case 1003:
    case 1004:
    case 1005:
    case 1006:
    case 1007:
    case 1008:
    case 1009:
    case 2000:
    case 2001:
    case 2002:
    case 2003:
    case 2004:
    case 2005:
    case 2006:
    case 2007:
    case 2008:
    case 2009:
    case 2010:
    case 2011:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MoveState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[1];
}
bool MoveState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ObjectType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[2];
}
bool ObjectType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PlayerType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[3];
}
bool PlayerType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* EquipPart_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_Enum_2eproto);
  return file_level_enum_descriptors_Enum_2eproto[4];
}
bool EquipPart_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 5:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
